// /sdapi/v1/samplers
export enum SamplingMethod {
    DPMPlusPlus2M = 'DPM++ 2M',
    DPMPlusPlusSDE = 'DPM++ SDE',
    DPMPlusPlus2MSDE = 'DPM++ 2M SDE',
    DPMPlusPlus2MSDEHeun = 'DPM++ 2M SDE Heun',
    DPMPlusPlus2S_a = 'DPM++ 2S a',
    DPMPlusPlus3MSDE = 'DPM++ 3M SDE',
    Euler_a = 'Euler a',
    Euler = 'Euler',
    LMS = 'LMS',
    Heun = 'Heun',
    DPM2 = 'DPM2',
    DPM2_a = 'DPM2 a',
    DPMFast = 'DPM fast',
    DPMAdaptive = 'DPM adaptive',
    Restart = 'Restart',
    DDIM = 'DDIM',
    DDIMCFGPlusPlus = 'DDIM CFG++',
    PLMS = 'PLMS',
    UniPC = 'UniPC',
    LCM = 'LCM',
    DDPM = 'DDPM',
    HeunPP2 = 'HeunPP2',
    IPNDM = 'IPNDM',
    IPNDM_V = 'IPNDM_V',
    DEIS = 'DEIS',
    FluxRealistic = '[Forge] Flux Realistic',
    FluxRealisticSlow = '[Forge] Flux Realistic (Slow)'
}
