export enum EnvironmentKey {
    AuthenticationToken = 'MUSEBOT_DISCORD_TOKEN',
    ChatChannels = 'MUSEBOT_DISCORD_CHANNELS',
    ChatChannelsDisallowed = 'MUSEBOT_DISCORD_CHANNELS_DISALLOWED',
    BotErrorMessage = 'MUSEBOT_ERROR_MESSAGE',
    BotFunction = 'MUSEBOT_FUNCTION',
    BotResponseRate = 'MUSEBOT_RESPONSE_RATE',
    BotRequiresMention = 'MUSEBOT_REQUIRES_MENTION',
    BotPrivateMessageUsers = 'MUSEBOT_PRIVATE_MESSAGE_USERS',
    NodeEnvironment = 'NODE_ENV',
    OllamaHosts = 'MUSEBOT_OLLAMA_HOSTS',
    OllamaModels = 'MUSEBOT_OLLAMA_MODELS',
    OllamaStreamsResponse = 'MUSEBOT_OLLAMA_STREAMS_RESPONSE',
    OllamaSystemPrompt = 'MUSEBOT_OLLAMA_SYSTEM_PROMPT',
    OllamaTaskChannel = 'MUSEBOT_TASK_QUEUE_CHANNEL_OLLAMA',
    StableDiffusionApiType = 'MUSEBOT_STABLE_DIFFUSION_API_TYPE',
    StableDiffusionHosts = 'MUSEBOT_STABLE_DIFFUSION_HOSTS',
    StableDiffusionOllamaPrompts = 'MUSEBOT_STABLE_DIFFUSION_OLLAMA_PROMPTS',
    StableDiffusionTaskChannel = 'MUSEBOT_TASK_QUEUE_CHANNEL_STABLE_DIFFUSION',
    TaskQueueMaxAttempts = 'MUSEBOT_TASK_QUEUE_MAX_ATTEMPTS',
    TaskQueueRetryDelayMs = 'MUSEBOT_TASK_QUEUE_RETRY_DELAY_MS',
}
