stages:
  - lint
  - transpile
  - deploy
  - build

Lint:
  stage: lint
  image: node:lts
  tags:
    - docker
  before_script:
    - npm install
  script:
    - npm run lint

Transpile:
  stage: transpile
  image: node:lts
  tags:
    - docker
  before_script:
    - npm install
  script:
    - npm run parcel

Deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:stable-dind
  only:
    - main
  tags:
    - docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/xcjs/musebot:latest .
    - docker push $CI_REGISTRY/xcjs/musebot:latest

Build:
  stage: build
  image: node:lts
  tags:
    - docker
  before_script:
    - npm install
  script:
    - npm run build:bin
    - cp -f .env.example build/pkg/.env
    - cp -rf docs/ build/pkg/docs/
    - cp -f logo.jpg build/pkg/logo.jpg
    - cp -f musebot.ico build/pkg/musebot.ico
    - mv build/pkg/musebot-linux build/pkg/musebot-linux-x86_64
    - mv build/pkg/musebot-macos build/pkg/musebot-macos-x86_64
    - mv build/pkg/musebot-win.exe build/pkg/musebot-win-x86_64.exe
  artifacts:
    name: musebot
    paths:
      - build/pkg/
    expire_in: 1 week
