FROM node:24 AS builder

WORKDIR /home/node/app
COPY . .

RUN npm ci && npm run docs:build

USER node

FROM nginx:latest

RUN mkdir /app

WORKDIR /app

COPY --from=builder /home/node/app/docs/dist /usr/share/nginx/html
