import { ControlNetUnit } from './models/ControlNetUnit';
import { SamplingMethod } from '../../enums/SamplingMethod';
import { ScheduleType } from '../../enums/ScheduleType';
import { Upscaler } from '../../enums/Upscaler';

export interface Txt2ImgOptionsRequest {
    enable_hr: boolean;
    hr_scale: number | null;
    hr_upscaler: Upscaler;
    hr_second_pass_steps?: number;
    hr_resize_x: number | null;
    hr_resize_y: number | null;
    denoising_strength: number | null;
    firstphase_width: number | null;
    firstphase_height: number | null;
    prompt: string | null;
    styles: string[];
    seed: number;
    subseed: number | null;
    subseed_strength?: number;
    seed_resize_from_h?: number;
    seed_resize_from_w?: number;
    batch_size: number | null;
    n_iter: number | null;
    steps: number | null;
    cfg_scale?: number;
    width?: number;
    height?: number;
    restore_faces?: boolean;
    tiling?: boolean;
    do_not_save_samples?: boolean;
    do_not_save_grid?: boolean;
    negative_prompt?: string;
    eta: number | null;
    s_churn: number | null;
    s_tmax: number | null;
    s_tmin: number | null;
    s_noise: number | null;
    override_settings?: Record<string, unknown>;
    override_settings_restore_afterwards?: boolean;
    script_name: string | null;
    send_images: boolean;
    save_images: boolean;
    controlnet_units: ControlNetUnit[];
    sampler_name: SamplingMethod;
    use_deprecated_controlnet?: boolean;
    scheduler: ScheduleType | null;
    distilled_cfg_scale: number;
    s_min_uncond: number;
    refiner_checkpoint: string | null;
    refiner_switch_at: number;
    disable_extra_networks: boolean;
    firstpass_image: string | null;
    comments: object;
    hr_checkpoint_name: string | null;
    hr_sampler_name: string | null;
    hr_scheduler: string | null;
    hr_prompt: string | null;
    hr_negative_prompt: string | null;
    force_task_id: string | null;
    sampler_index: SamplingMethod;
    script_args: Array<string> | null;
    alwayson_scripts: Record<string, unknown> | null;
    infotext: string | null;
}
