import { DatEnabledModel } from '../../../../../automatic1111/models/requests/enums/DatEnabledModel.js';
import { ImageFormat } from '../../../../../automatic1111/models/requests/enums/ImageFormat.js';
import { KeyEditDelimiterWhitespace } from '../../../../../automatic1111/models/requests/enums/KeyEditDelimiterWhitespace.js';
import { ProfilingActivity } from '../../../../../automatic1111/models/requests/enums/ProfilingActivity.js';
import { RealEsrganEnabledModel } from '../../../../../automatic1111/models/requests/enums/RealEsrganEnabledModel.js';
import { SaveImagesReplaceAction } from '../../../../../automatic1111/models/requests/enums/SaveImagesReplaceAction.js';

export class Automatic1111Options {
  samples_save: boolean = true;
  samples_format: ImageFormat = ImageFormat.Png;
  samples_filename_pattern: string = "";
  save_images_add_number: boolean = true;
  save_images_replace_action: SaveImagesReplaceAction = SaveImagesReplaceAction.Replace;
  grid_save: boolean = true;
  grid_format: ImageFormat = ImageFormat.Png;
  grid_extended_filename: boolean = false;
  grid_only_if_multiple: boolean = true;
  grid_prevent_empty_spots: boolean = false;
  grid_zip_filename_pattern: string = '';
  n_rows: number = -1;
  font: string = '';
  grid_text_active_color: string = '#000000';
  grid_text_inactive_color: string = '#999999';
  grid_background_color: string = '#ffffff';
  save_images_before_face_restoration: boolean = false;
  save_images_before_highres_fix: boolean = false;
  save_images_before_color_correction: boolean = false;
  save_mask: boolean = false;
  save_mask_composite: boolean = false;
  jpeg_quality: number = 80;
  webp_lossless: boolean = false;
  export_for_4chan: boolean = true;
  img_downscale_threshold: number = 4;
  target_side_length: number = 4000;
  img_max_size_mp: number = 200;
  use_original_name_batch: boolean = true;
  use_upscaler_name_as_suffix: boolean = false;
  save_selected_only: boolean = true;
  save_write_log_csv: boolean = true;
  save_init_img: boolean = false;
  temp_dir: string = '';
  clean_temp_dir_at_start: boolean = false;
  save_incomplete_images: boolean = false;
  notification_audio: boolean = true;
  notification_volume: number = 100;
  outdir_samples: string = '';
  outdir_txt2img_samples: string = 'outputs/txt2img-images';
  outdir_img2img_samples: string = 'outputs/img2img-images';
  outdir_extras_samples: string = 'outputs/extras-images';
  outdir_grids: string = '';
  outdir_txt2img_grids: string = 'outputs/txt2img-grids';
  outdir_save: string = 'log/images';
  outdir_init_images: string = 'outputs/init-images';
  save_to_dirs: boolean = true;
  grid_save_to_dirs: boolean = true;
  use_save_to_dirs_for_ui: boolean = false;
  directories_filename_pattern: string = '[date]';
  directories_max_prompt_words: number = 8;
  ESRGAN_tile: number = 192;
  ESRGAN_tile_overlap: number = 8;

  realesrgan_enabled_models: Array<RealEsrganEnabledModel> = [
    RealEsrganEnabledModel.RESRGAN4xPlus,
    RealEsrganEnabledModel.RESRGAN4xPlusAnime6B
  ];

  dat_enabled_models: Array<DatEnabledModel> = [
    DatEnabledModel.DATx2,
    DatEnabledModel.DATx3,
    DatEnabledModel.DATx3
  ];

  DAT_tile: number =  192;
  DAT_tile_overlap: number = 8;
  upscaler_for_img2img: string = 'string';
  set_scale_by_when_changing_upscaler: boolean = false;
  face_restoration: boolean = false;
  face_restoration_model: string = 'CodeFormer';
  code_former_weight: number = 0.5;
  face_restoration_unload: boolean = false;
  auto_launch_browser: 'Local';
  enable_console_prompts: boolean = false;
  show_warnings: boolean = false;
  show_gradio_deprecation_warnings: boolean = true;
  memmon_poll_rate: number = 8;
  samples_log_stdout: boolean = false;
  multiple_tqdm: boolean = true;
  enable_upscale_progressbar: boolean = true;
  print_hypernet_extra: boolean = false;
  list_hidden_files: boolean = true;
  disable_mmap_load_safetensors: boolean = false;
  hide_ldm_prints: boolean = true;
  dump_stacks_on_signal: boolean = false;
  profiling_explanation: string = 'Those settings allow you to enable torch profiler when generating pictures.\nProfiling allows you to see which code uses how much of computer\'s resources during generation.\nEach generation writes its own profile to one file, overwriting previous.\nThe file can be viewed in <a href="chrome:tracing">Chrome</a>, or on a <a href="https://ui.perfetto.dev/">Perfetto</a> web site.\nWarning: writing profile can take a lot of time, up to 30 seconds, and the file itself can be around 500MB in size.';
  profiling_enable: boolean = false;

  profiling_activities: Array<ProfilingActivity> = [
    ProfilingActivity.CPU
  ];

  profiling_record_shapes: boolean = true;
  profiling_profile_memory: boolean = true;
  profiling_with_stack: boolean = true;
  profiling_filename: string = 'trace.json';
  api_enable_requests: boolean = true;
  api_forbid_local_requests: boolean = true;
  api_useragent: string = '';
  unload_models_when_training: boolean = false;
  pin_memory: boolean = false;
  save_optimizer_state: boolean = false;
  save_training_settings_to_txt: boolean = true;
  dataset_filename_word_regex: string = '';
  dataset_filename_join_string: string = ' ';
  training_image_repeats_per_epoch: number = 1;
  training_write_csv_every: number = 500;
  training_xattention_optimizations: boolean = false;
  training_enable_tensorboard: boolean = false;
  training_tensorboard_save_images: boolean = false;
  training_tensorboard_flush_every: number = 120;
  sd_model_checkpoint: string = 'string';
  sd_checkpoints_limit: number = 1;
  sd_checkpoints_keep_in_cpu: boolean = true;
  sd_checkpoint_cache: string = '0';
  sd_unet: string = 'Automatic';
  enable_quantization: boolean = false;
  emphasis: string = 'Original';
  enable_batch_seeds: boolean = true;
  comma_padding_backtrack: number = 20;
  sdxl_clip_l_skip: boolean = false;
  CLIP_stop_at_last_layers: number = 1;
  upcast_attn: boolean = false;
  randn_source: string = 'GPU';
  tiling: boolean = false;
  hires_fix_refiner_pass: string = 'second pass';
  sdxl_crop_top: string = '0';
  sdxl_crop_left: string = '0';
  sdxl_refiner_low_aesthetic_score: number = 2.5;
  sdxl_refiner_high_aesthetic_score: number = 6;
  sd3_enable_t5: boolean = false;
  sd_vae_explanation: string =  '<abbr title=\'Variational autoencoder\'>VAE</abbr> is a neural network that transforms a standard <abbr title=\'red/green/blue\'>RGB</abbr>\nimage into latent space representation and back. Latent space representation is what stable diffusion is working on during sampling\n(i.e. when the progress bar is between empty and full). For txt2img, VAE is used to create a resulting image after the sampling is finished.\nFor img2img, VAE is used to process user\'s input image before the sampling, and to create an image after sampling.';
  sd_vae_checkpoint_cache: string = '0';
  sd_vae: 'Automatic';
  sd_vae_overrides_per_model_preferences: boolean =  true;
  auto_vae_precision_bfloat16: boolean = false;
  auto_vae_precision: boolean = true;
  sd_vae_encode_method: 'Full';
  sd_vae_decode_method: 'Full';
  inpainting_mask_weight: number = 1;
  initial_noise_multiplier: number = 1;
  img2img_extra_noise: string = '0';
  img2img_color_correction: boolean = false;
  img2img_fix_steps: boolean = false;
  img2img_background_color: string = '#ffffff';
  img2img_sketch_default_brush_color: string = '#ffffff';
  img2img_inpaint_mask_brush_color: string = '#ffffff';
  img2img_inpaint_sketch_default_brush_color: string = '#ffffff';
  img2img_inpaint_mask_high_contrast: boolean = true;
  return_mask: boolean = false;
  return_mask_composite: boolean = false;
  img2img_batch_show_results_limit: number = 32;
  overlay_inpaint: boolean = true;
  img2img_autosize: boolean = false;
  cross_attention_optimization: string = 'Automatic';
  s_min_uncond: string = '0';
  s_min_uncond_all: boolean = false;
  token_merging_ratio: string = '0';
  token_merging_ratio_img2img: string = '0';
  token_merging_ratio_hr: string = '0';
  pad_cond_uncond: boolean = false;
  pad_cond_uncond_v0: boolean = false;
  persistent_cond_cache: boolean = true;
  batch_cond_uncond: boolean = true;
  fp8_storage: string = 'Disable';
  cache_fp16_weight: boolean = false;
  forge_try_reproduce: string = 'None';
  auto_backcompat: boolean = true;
  use_old_emphasis_implementation: boolean = false;
  use_old_karras_scheduler_sigmas: boolean = false;
  no_dpmpp_sde_batch_determinism: boolean = false;
  use_old_hires_fix_width_height: boolean = false;
  hires_fix_use_firstpass_conds: boolean = false;
  use_old_scheduling: boolean = false;
  use_downcasted_alpha_bar: boolean = false;
  refiner_switch_by_sample_steps: boolean = false;
  interrogate_keep_models_in_memory: boolean = false;
  interrogate_return_ranks: boolean = false;
  interrogate_clip_num_beams: number = 1;
  interrogate_clip_min_length: number = 24;
  interrogate_clip_max_length: number = 48;
  interrogate_clip_dict_limit: number = 1500;
  interrogate_clip_skip_categories: Array<unknown> = [];
  interrogate_deepbooru_score_threshold: number = 0.5;
  deepbooru_sort_alpha: boolean = true;
  deepbooru_use_spaces: boolean = true;
  deepbooru_escape: boolean = true;
  deepbooru_filter_tags: string =  '';
  extra_networks_show_hidden_directories: boolean = true;
  extra_networks_dir_button_function: boolean = false;
  extra_networks_hidden_models: string = 'When searched';
  extra_networks_default_multiplier: number = 1;
  extra_networks_card_width: string = '0';
  extra_networks_card_height: string = '0';
  extra_networks_card_text_scale: number = 1;
  extra_networks_card_show_desc: boolean = true;
  extra_networks_card_description_is_html: boolean = false;
  extra_networks_card_order_field: string = 'Path';
  extra_networks_card_order: 'Ascending';
  extra_networks_tree_view_style: string = 'Dirs';
  extra_networks_tree_view_default_enabled: boolean = true;
  extra_networks_tree_view_default_width: number = 180;
  extra_networks_add_text_separator: string= ' ';
  ui_extra_networks_tab_reorder: string = '';
  textual_inversion_print_at_load: boolean = false;
  textual_inversion_add_hashes_to_infotext: boolean = true;
  sd_hypernetwork: string = 'None';
  keyedit_precision_attention: number = 0.1;
  keyedit_precision_extra: number = 0.05;
  keyedit_delimiters: '.,\\/!?%^*;:{}=`~() ';

  keyedit_delimiters_whitespace: Array<KeyEditDelimiterWhitespace> = [
    KeyEditDelimiterWhitespace.Tab,
    KeyEditDelimiterWhitespace.CarriageReturn,
    KeyEditDelimiterWhitespace.LineFeed
  ];

  keyedit_move: boolean = true;
  disable_token_counters: boolean = false;
  include_styles_into_token_counters: boolean = true;
  return_grid: boolean = true;
  do_not_show_images: boolean = false;
  js_modal_lightbox: boolean = true;
  js_modal_lightbox_initially_zoomed: boolean = true;
  js_modal_lightbox_gamepad: boolean = false;
  js_modal_lightbox_gamepad_repeat: number = 250;
  sd_webui_modal_lightbox_icon_opacity: number = 1;
  sd_webui_modal_lightbox_toolbar_opacity: number = 0.9;
  gallery_height: string = '';
  open_dir_button_choice: string = 'Subdirectory';
  compact_prompt_box: boolean = false;
  samplers_in_dropdown: boolean = true;
  dimensions_and_batch_together: boolean = true;
  sd_checkpoint_dropdown_use_short: boolean = false;
  hires_fix_show_sampler: boolean = false;
  hires_fix_show_prompts: boolean = false;
  txt2img_settings_accordion: boolean = false;
  img2img_settings_accordion: boolean = false;
  interrupt_after_current: boolean = true;
  localization: string = 'None';
  quick_setting_list: Array<unknown> = [];
  ui_tab_order: Array<unknown> = [];
  hidden_tabs: Array<unknown> = [];
  ui_reorder_list: Array<unknown> = [];
  gradio_theme: string = 'Default';
  gradio_themes_cache: boolean = true;
  show_progress_in_title: boolean = true;
  send_seed: boolean = true;
  send_size: true;
  enable_reloading_ui_scripts: boolean = false;
  infotext_explanation: string = 'Infotext is what this software calls the text that contains generation parameters and can be used to generate the same picture again.\nIt is displayed in UI below the image. To use infotext, paste it into the prompt and click the ↙️ paste button.';
  enable_pnginfo: boolean = true;
  save_txt: boolean = false;
  add_model_name_to_info: boolean = true;
  add_model_hash_to_info: boolean = true;
  add_vae_name_to_info: boolean = true;
  add_vae_hash_to_info: boolean = true;
  add_user_name_to_info: boolean = false;
  add_version_to_infotext: boolean = true;
  disable_weights_auto_swap: boolean = true;
  infotext_skip_pasting: Array<unknown> = [];
  infotext_styles: string = 'Apply if unknown';
  show_progressbar: boolean = true;
  live_previews_enable: boolean = true;
  live_previews_image_format: ImageFormat = ImageFormat.Png;
  show_progress_grid: boolean = true;
  show_progress_every_n_steps: number = 10;
  show_progress_type: string = 'Approx NN';
  live_preview_allow_lowvram_full: boolean = false;
  live_preview_content: string = 'Prompt';
  live_preview_refresh_period: number = 1000;
  live_preview_fast_interrupt: boolean = false;
  js_live_preview_in_modal_lightbox: boolean = false;
  prevent_screen_sleep_during_generation: boolean = true;
  hide_samplers: Array<unknown> = [];
  eta_ddim: string = "0";
  eta_ancestral: number = 1;
  ddim_discretize: string = 'uniform';
  s_churn: string = '0';
  s_tmin: string = '0';
  s_tmax: string = '0';
  s_noise: number = 1;
  sigma_min: string = '0';
  sigma_max: string = '0';
  rho: string = '0';
  eta_noise_seed_delta: string = '0';
  always_discard_next_to_last_sigma: boolean = false;
  sgm_noise_multiplier: boolean = false;
  uni_pc_variant: string = 'bh1';
  uni_pc_skip_type: string = 'time_uniform';
  uni_pc_order: number = 3;
  uni_pc_lower_order_final: boolean = true;
  sd_noise_schedule: string = 'Default';
  skip_early_cond: string = '0';
  beta_dist_alpha: number = 0.6;
  beta_dist_beta: number = 0.6;
  postprocessing_enable_in_main_ui: Array<unknown> = [];
  postprocessing_disable_in_extras: Array<unknown> = [];
  postprocessing_operation_order: Array<unknown> = [];
  upscaling_max_images_in_cache: number = 5;
  postprocessing_existing_caption_action: string = 'Ignore';
  disabled_extensions: Array<unknown> = [];
  disable_all_extensions: string = 'none';
  restore_config_state_file: string = '';
  sd_checkpoint_hash: string = '';
  forge_unet_storage_dtype: string = 'Automatic';
  forge_inference_memory: number = 1024;
  forge_async_loading: 'Queue';
  forge_pin_shared_memory: string = "CPU";
  forge_preset: string = 'sd';
  forge_additional_modules: Array<unknown> = [];
  sd_t2i_width: number = 512;
  sd_t2i_height: number = 640;
  sd_t2i_cfg: number = 7;
  sd_t2i_hr_cfg: number = 7;
  sd_i2i_width: number = 512;
  sd_i2i_height: number = 512;
  sd_i2i_cfg: number = 7;
  xl_t2i_width: number = 896;
  xl_t2i_height: number = 1152;
  xl_t2i_cfg: number = 5;
  xl_t2i_hr_cfg: number = 5;
  xl_i2i_width: number = 1024;
  xl_i2i_height: number = 1024;
  xl_i2i_cfg: number = 5;
  flux_t2i_width: number = 896;
  flux_t2i_height: number = 1152;
  flux_t2i_cfg: number = 1;
  flux_t2i_hr_cfg: number = 1;
  flux_t2i_d_cfg: number = 3.5;
  flux_t2i_hr_d_cfg: number = 3.5;
  flux_i2i_width: number = 1024;
  flux_i2i_height: number = 1024;
  flux_i2i_cfg: number = 1;
  flux_i2i_d_cfg: number = 3.5;
  settings_in_ui: 'This page allows you to add some settings to the main interface of txt2img and img2img tabs.';
  extra_options_txt2img: Array<unknown> = [];
  extra_options_img2img: Array<unknown> = [];
  extra_options_cols: number = 1;
  extra_options_accordion: boolean = false;

  constructor() {

  }
}
