name: XCJS Ollama (LAN)
version: 1.0.0
schema: v1
models:
  - name: XCJS Ollama (LAN)
    provider: ollama
    defaultCompletionOptions:
     contextLength: 16384
    model: AUTODETECT
    apiBase: http://ai.lan:11434
    roles:
      - apply
      - autocomplete
      - chat
      - edit
      - summarize
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
