name: LeadingEDJE LiteLLM
version: 1.0.0
schema: v1

models:
  - name: LeadingEDJE LiteLLM
    provider: openai
    apiBase: https://litellm.leadingedje.com/v1
    apiKey: '${{secrets.LE_LITELLM_TOKEN}}'
    model: AUTODETECT
    roles:
      - apply
      - autocomplete
      - chat
      - edit
      - summarize

context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
